config/routes.rb
Sudzie::Application.routes.draw do
   
  devise_for :users

   root :to => 'pages#home'
   get 'about' => 'pages#about'
   get 'contact' => 'pages#contact'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_footer.html.erb
<div class="footer">
</div>

app/views/layouts/_header.html.erb
<div class= "navbar navbar-fixed-top">
	<div class="navbar-inner">
		<div class="container">
			<a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
				<span class="icon-bar"> </span>
				<span class="icon-bar"> </span>
				<span class="icon-bar"> </span>
			</a>
				<p class="navbar-text">
					<h1>sudzie</h1>
				</p>
				<div class="nav-collapse">
					<ul class="nav">
						<li>
							<%= link_to 'Home', root_path %>
						</li>
						<li>
							<%= link_to 'About', about_path %>
						</li>
						<li>
							<%= link_to 'Contact', contact_path %>
						</li>
					</ul>
					<ul class="nav pull-right">
						<li> <% link_to 'Login', '#' %></li>
					</ul>
				</div>
		</div>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>One Month Rails</title>
	  <%= stylesheet_link_tag    "application", :media => "all" %>
	  <%= javascript_include_tag "application" %>
	  <%= csrf_meta_tags %>
	</head>
	<body>
	<%= render 'layouts/header' %>
	 <div class="container">
			<% flash.each do |name, msg| %>
				<%= content_tag(:div, msg, class: "alert alert-#{name}") %>
				<% end %>
			<%= yield %>
			<%= render 'layouts/footer' %>
		</div>

	</body>
</html>

app/views/pages/about.html.erb
<h1>About!!!!</h1>
<p>
</p>

app/views/pages/home.html.erb
	<% if user_signed_in? %>
		<div class="center hero-unit">

		</div>

<% else %>

<div class="center hero-unit">
	<h1>#GPS MAP#</h1>
</div>

<div class="well">
	<h1>Welcome to sudzie</h1>
	<p>
	You've found the home page for sudzie. Sign up below
	</p>
	<p>
	 <%= link_to "Sign Up Now!", new_user_registration_path, class: "btn btn-primary btn-large" %>
	</p>
</div>
<% end %>